### ISSUE TITLE
Distorted Icons in Windows

### ISSUE THREAD

**Issue by GochoMugo** [Swatto/td#20]
The tick (:heavy_check_mark:) and cross (:heavy_multiplication_x:) are distorted in Windows.

On Window's **cmd**:
![bug-td-cmd](https://cloud.githubusercontent.com/assets/4707579/7268694/be188ad2-e8d4-11e4-946a-4f45f812c8f4.png)

On **mingw32**:
![bug-td-mingw32](https://cloud.githubusercontent.com/assets/4707579/7268700/c7277f5c-e8d4-11e4-87d4-395ba77963a0.png)

More information:
* running on Windows 8

**Comment by Swatto** [comment]
I'm sorry but I don't have a computer with Windows so I can't work on that issue.

**Comment by txgruppi** [comment]
I can make a quick fix. I will just remove the symbols and use only ASCII characters.

To make it right someone who uses Windows (I can't use it, I'm allergic) could find a solution,

**Comment by Swatto** [comment]
ASCII characters are a bit limited from my point of view.
We should investigate on supported symbols on Windows before choosing the easy solution.

**Comment by txgruppi** [comment]
Agreed

**Comment by Swatto** [comment]
I'm not sure that I will have the time to work on this today but tomorrow for sure !

**Comment by Swatto** [comment]
It looks like the character encoding of the Windows command line still use an old character encoding (Code page 437 and Code page 850 for Western Europe), not UTF-8.

Since I have no idea of how handle this, @GochoMugo could you test this and tell us if it works:

- Change the font of the command line to Lucida console;
- Execute `chcp 65001` to switch to UTF-8.

If yes, we could reference this in our README.
If not, we could use the `PATH_SEPARATOR` to detect the current OS and use ASCII for Windows:

- `\\` for Windows
- `/` for Unix

What do you think of this guys?

**Comment by txgruppi** [comment]
I agree that we should display a different output on Windows but instead of using the `PATH_SEPARATOR` we can use build information http://golang.org/pkg/go/build/#Context or platform specific files like `printer_windows.go` for windows and `printer.go` for anything else.

More information about OS specific code can be found at http://golang.org/pkg/go/build

**Comment by GochoMugo** [comment]
1. Changing font to **Lucida Console**:
![td_font](https://cloud.githubusercontent.com/assets/4707579/7387988/7aa0e04c-ee6a-11e4-8013-6426d4b1a94c.png)
2. Executing `chcp 65001` to switch to UTF-8:
![td_chcp](https://cloud.githubusercontent.com/assets/4707579/7388006/95b613e8-ee6a-11e4-84af-2d2ffc30e5f9.png)

Result:
* the characters are still distorted

That does **not** seem to work!

**Comment by Swatto** [comment]
@txgruppi could you check this 93a0d09593d455d438d832cc59a08d367c95081d. I think it will solve the issue but I'm not used to work with Go specific platform code.

**Comment by txgruppi** [comment]
@Swatto I just found out that using the filename suffix can specify which OS to include the file but not which OS to **not** include it.

I tested here and the best option will be to **also** use the `+build` tag. At the beginning of each file you will add `// +build` followed by the rule, in this case `// +build windows` for `_windows` and `// +build !windows` for normal. It is important to have a blank line after this tag:

```go
// +build windows

package printer

...
```

I'm not sure about this one: `package Printer` or `package printer`? Can a package name use uppercase?

**Comment by Swatto** [comment]
Since the blank line is already here, I will only change the

```go
// +build linux darwin

package Printer
```

to

```go
// +build !windows

package Printer
```

Also since every packages use non-uppercase, I will follow the convention but it looks like it works in both cases.
