### ISSUE TITLE
Is Godeps needed?

### ISSUE THREAD

**Issue by txgruppi** [Swatto/td#22]
I believe Godeps is not updated and maybe nobody is using it. Does someone disagree?

**Comment by Swatto** [comment]
It's true that Godep doesn't receive update but for the moment, it looks like the only viable dependencies manager for Go now.

But do we need something to do this job? Do we need a dependencies manager?

I think so: I don't want to have collision with possible other versions. For example, I use a release of the *cli* project (from codegangsta), but this release has almost 6 months and lot of changes as been pushed now on the master branch.

I look at some repos of big project and there are still using it (Vault, Rkt, etcd, etc...) but if you have an other one, I could look at it.

**Comment by txgruppi** [comment]
I'm not a big fan of Godeps (or any other tool that plays with env vars or import paths)

I like this one: https://github.com/joewalnes/go-getter

It is a simple shell script which just use a file to know which version of what it should use

**Comment by Swatto** [comment]
Ok for the altenative but there's still an external tool to install, `chmod`, etc... So it's not a cleaner alternative from my point of view.

I understand what you mean and I get the difference between those projects but since one is more commun than the other and the same kind of use, I prefer **for the moment** to stay with Godep.

**Comment by txgruppi** [comment]
Yes. Better to stay with something stable. It was just a suggestion.

**Comment by Swatto** [comment]
Every suggestion should be discussed. So no problem !
