### ISSUE TITLE
Modifying list items

### ISSUE THREAD

**Issue by aratno** [Swatto/td#28]
This is a matter of preference, but I think most people would agree that rewriting an entire item just to modify a detail is too much effort. On typing `td m 1`, the old message should be displayed for editing, rather than having to retype the entire thing. This is especially arduous for adding a tag to the end of an item.

**Comment by Swatto** [comment]
The global idea of `td` is to never prompt question for the end-user so command could be automated. Your proposition is nice but it goes the other way.

**Comment by aratno** [comment]
How about a way to append to an item then?

**Comment by Swatto** [comment]
Since the storage is a simple JSON file, if you really want to do that kind of modification, you can do it by hand. The idea is not to provide a full featured CLI but a simple project that is easy to maintained by new people. But if you *really* wanted to achieve this, here is a simple command to modify with a prepend:

```bash
~ td a "Super test"
#1 "Super test" is now added to your todos.
~ td

     1 | ✕ Super test

~ td m 1 "Prepend $(td | grep "1 " | cut -d "|" -f2 | cut -c17-)"
"1" has now a new description: Prepend Super test
```

In the commande `td | grep "1 " | cut -d "|" -f2 | cut -c17-)`, the `"1 "` is the id of the todo that you want to modify.
